# Generated by Django 5.0.6 on 2024-05-27 09:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=255)),
                ('exam_desc', models.TextField()),
                ('exam_branch', models.CharField(max_length=255)),
                ('exam_passkey', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('exam_date', models.DateField()),
                ('exam_start_time', models.TimeField()),
                ('exam_end_time', models.TimeField()),
                ('is_completed', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
