# Generated by Django 5.0.6 on 2024-05-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammodel',
            name='exam_passkey',
            field=models.CharField(max_length=255),
        ),
    ]
