# Generated by Django 5.0.6 on 2024-05-27 10:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0002_alter_exammodel_exam_passkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammodel',
            name='exam_passkey',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
