# Generated by Django 5.0.6 on 2024-05-28 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0003_alter_exammodel_exam_passkey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBoxModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer1', models.CharField(max_length=255)),
                ('answer2', models.CharField(max_length=255)),
                ('answer3', models.CharField(blank=True, max_length=255)),
                ('answer4', models.CharField(blank=True, max_length=255)),
                ('currect_answer', models.CharField(max_length=255)),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.exammodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
