# Generated by Django 5.0.6 on 2024-05-28 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0004_questionboxmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionboxmodel',
            old_name='currect_answer',
            new_name='currectanswer',
        ),
    ]
