# Generated by Django 5.0.6 on 2024-05-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0005_rename_currect_answer_questionboxmodel_currectanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammodel',
            name='exam_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
