# Generated by Django 5.0.4 on 2024-05-05 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile', models.CharField(choices=[('admin', 'admin'), ('faculty', 'faculty'), ('student', 'student')], max_length=50)),
                ('user_title', models.CharField(blank=True, max_length=50)),
                ('user_mobile_no', models.CharField(blank=True, max_length=50)),
                ('user_date_of_birth', models.CharField(blank=True, max_length=50)),
                ('user_gender', models.CharField(blank=True, max_length=50)),
                ('user_address', models.TextField()),
                ('user_city', models.CharField(blank=True, max_length=255)),
                ('user_pin_code', models.CharField(blank=True, max_length=255)),
                ('user_country', models.CharField(blank=True, max_length=255)),
                ('user_identity', models.CharField(blank=True, max_length=255)),
                ('identity_image', models.FileField(blank=True, upload_to='identity_images/')),
                ('admin_institute', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
