# Generated by Django 5.0.6 on 2024-05-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_profile_user_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='profile',
            field=models.CharField(choices=[('faculty', 'faculty'), ('student', 'student')], max_length=50),
        ),
    ]
