# Generated by Django 5.0.1 on 2024-05-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=255)),
                ('branch_description', models.TextField()),
            ],
        ),
    ]
